version: "3"
services:
  node:
    image: node:22
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
    ports:
      - 4000:4000
    command: "bash -c 'npm install && npm run start'"
